### ISSUE TITLE
how use hxsl3

### ISSUE THREAD

**Issue by matrix3d** [ncannasse/heaps#100]
i copy the hxsl2 code ,not work in hxsl3.

and i see the h3d shader code.but can not get how use also.

my code

class TestShader extends Shader {
	static var SRC = { 
		var output : {
			var position : Vec4;
			var color : Vec4;
		};
		
		function vertex() {
			output.position =[1.,1,1,1];
		}
		function fragment() {
			output.color = [1.,1,1,1];
		}
	};
	
	public function new() {
		super();	
	}
}

Float[4] should be Vec4

**Comment by ncannasse** [comment]
HXSL3 uses GLSL semantics, so you need to use `vec4(1.,1.,1.,1.)`

**Comment by matrix3d** [comment]
i just use the hxsl3,not h3d.i use the shader swc in my as project.
but how get the agal code from the shader.
and where the shaderinstance of the hxsl2?

**Comment by ncannasse** [comment]
hxsl3 is more powerful but more complex to use than hxsl2, look at heaps sources to see how it's used (h3d.impl.Stage3dDriver compiles to AGAL)
