### ISSUE TITLE
The getting started example only works in with -debug flag on js target

### ISSUE THREAD

**Issue by bubblebenj** [ncannasse/heaps#104]
I found out that the very first example in the documentation only display a black canvas in release (FD not -debug).
https://github.com/ncannasse/heaps/wiki/Getting-Started

I tested targeting flash, -debug and release work as expected

**Comment by ncannasse** [comment]
Seems to work on my computer. Do you get any console error ?

**Comment by bubblebenj** [comment]
Yes I forget it (On firefox)
testheaps.js (line 12130, col 16)
TypeError: this.resolver.resolveEnum is not a function
	var edecl1 = this.resolver.resolveEnum(name2);

**Comment by bubblebenj** [comment]
I've got the same result on Chrome.
Are there any compile flag that could add to have a less obfuscated code ?
The line in this context :
```javascript
		case 106:
			var name2 = this.unserialize();
			var edecl1 = this.resolver.resolveEnum(name2);
			if(edecl1 == null) throw new js__$Boot_HaxeError("Enum not found " + name2);
			this.pos++;
			var index = this.readDigits();
			var tag = Type.getEnumConstructs(edecl1)[index];
			if(tag == null) throw new js__$Boot_HaxeError("Unknown enum index " + name2 + "@" + index);
			var e1 = this.unserializeEnum(edecl1,tag);
			this.cache.push(e1);
			return e1;
```

**Comment by ncannasse** [comment]
It should use Type.resolveEnum, what compilation flags are you using ? which Haxe version ?

**Comment by bubblebenj** [comment]
Haxe 3.2 (Official), the FD generated hxml is
```
-lib heaps
-cp src
-js bin/testheaps.js
-main Main
```

**Comment by ncannasse** [comment]
Does it works better with `-dce no` ?

**Comment by bubblebenj** [comment]
Yes it does :)

**Comment by bubblebenj** [comment]
OK, so unless it is an unexpected behavior, I'll edit the wiki so that first example doesn't fail :)
