### ISSUE TITLE
Haxe 3.1.3 incompatibility

### ISSUE THREAD

**Issue by jonongjs** [ncannasse/heaps#105]
The development version of Heaps requires Haxe >= 3.2. Is this intended? I can help with 3.1.3 compatibility if it's needed, though I'm not too sure about the amount of effort required.

**Comment by ncannasse** [comment]
If you can come up with a small PR that keep 3.1.3 compat it's ok for me - I've not look at which changes are needed - but since Heaps is not yet officially released (although quite stable) I'm not willing to keep a lot of backward compatibility yet.

**Comment by jonongjs** [comment]
One of the major issues seems to stem from hxd.snd.Worker and related classes requiring haxe.io.Float32Array. I'm not sure if it would be meaningful to replicate that part of the standard library. I guess it would be better to close this issue, and update the wiki to indicate that Heaps requires Haxe >= 3.2?

**Comment by ncannasse** [comment]
Yes, seems better that way
