### ISSUE TITLE
GLSL compilation with helper functions

### ISSUE THREAD

**Issue by ncannasse** [ncannasse/heaps#115]
ATM it is not possible to compile GLSL code for shaders which contains helper functions (sample/SAO)

**Comment by ncannasse** [comment]
Because of the lighting shaders change in https://github.com/ncannasse/heaps/commit/da87ea910fd35a479e016b28495442656612403a this breaks all GL samples, will try to fix it asap

**Comment by delahee** [comment]
Thanks !

2015-11-18 20:29 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Closed #115 <https://github.com/ncannasse/heaps/issues/115> via 088249e
> <https://github.com/ncannasse/heaps/commit/088249e2c00dafb6532fc83951d007b1b7de276e>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncannasse/heaps/issues/115#event-468350604>.
>



-- 
David Elahee
