### ISSUE TITLE
blender fbx parser error

### ISSUE THREAD

**Issue by matrix3d** [ncannasse/heaps#121]
<pre>Deformer: "SubDeformer::Cluster boy root", "Cluster" {
		Version: 100
		MultiLayer: 0
		Type: "Cluster"
		Properties60:  {
			Property: "SrcModel", "object", ""
			Property: "SrcModelReference", "object", ""
		}
		UserData: "", ""
		Indexes: 
		Weights: 
		Transform: -14.639716148376465,-0.000001105267870,0.000000000000000,0.000000000000000,0.000001100516670,-14.576785087585449,-1.355974912643433,0.000000000000000,0.000000102373264,-1.355974912643433,14.576785087585449,0.000000000000000,-0.000000023131809,0.306390106678009,-2.821930646896362,1.000000000000000
		TransformLink: -0.025399999693036,0.000000000177618,-0.000000001909403,0.000000000000000,-0.000000001917647,-0.002352624898776,0.025290811434388,0.000000000000000,0.000000000000000,0.025290811434388,0.002352624898776,0.000000000000000,0.000000000000000,0.072089739143848,-0.001109909266233,1.000000000000000
	}</pre>

the error pos is
indexes:

**Comment by ncannasse** [comment]
That does not sound valid FBX, there is no data for both Indexes and Weights.

**Comment by matrix3d** [comment]
it is just no data.and the fbx can import good,with 3dmax.

**Comment by ncannasse** [comment]
Could you make this FBX available somewhere so I can try it ?

**Comment by matrix3d** [comment]
http://pan.baidu.com/s/1dDty6Hz
