### ISSUE TITLE
Getting Started example does not compile

### ISSUE THREAD

**Issue by TiZ-EX1** [ncannasse/heaps#122]
Since there's not a stable release on haxelib, all I can do is use git HEAD. I copied the getting started program from the wiki verbatim, and when attempting to compile, got the following compile errors:

    WC130-TiZ:Heaps$ haxe -main Main -lib heaps -cpp .hxcpp
    /home/common/confdata/haxelib/heaps/git/h3d/impl/GlDriver.hx:46: characters 8-24 : Type not found : Program
    /home/common/confdata/haxelib/heaps/git/h3d/Engine.hx:4: lines 4-323 : Defined in this class
    /home/common/confdata/haxelib/heaps/git/h3d/impl/GlDriver.hx:32: characters 8-25 : Type not found : GLShader

This is on Xubuntu 14.04 and Haxe 3.2.1.

**Comment by TiZ-EX1** [comment]
I poked around myself a bit and saw that the referenced line in GlDriver messed up because I hadn't specified a backend to use this with. But when I included `-lib nme` before `-lib heaps`, I instead got the following error: `hxd/BitmapData.hx:3: characters 0-25 : You cannot access the flash package while targeting cpp (for flash.display.BitmapData)`. I googled it and found the suggestion to use the macro `allowPackage("flash")`. Then I got even more errors!

    /home/common/confdata/haxelib/heaps/git/hxd/Stage.hx:42: characters 2-13 : Unknown identifier : initGesture
    /home/common/confdata/haxelib/heaps/git/h3d/impl/GlDriver.hx:224: characters 12-59 : nme.utils.Float32Array has no field subarray
    /home/common/confdata/haxelib/heaps/git/h3d/impl/GlDriver.hx:233: characters 12-58 : nme.utils.Float32Array has no field subarray
    /home/common/confdata/haxelib/heaps/git/hxd/BitmapData.hx:353: characters 57-80 : flash.utils.ByteArray should be haxe.io.BytesData
    /home/common/confdata/haxelib/heaps/git/hxd/BitmapData.hx:353: characters 57-80 : flash.utils.ByteArray should be Array<haxe.io.Unsigned_char__>
    /home/common/confdata/haxelib/heaps/git/hxd/BitmapData.hx:353: characters 57-80 : For function argument 'b'
    /home/common/confdata/haxelib/heaps/git/hxd/System.hx:95: characters 32-36 : nme.display.OpenGLView should be flash.display.DisplayObject
    /home/common/confdata/haxelib/heaps/git/hxd/System.hx:95: characters 32-36 : For function argument 'child'
    /home/common/confdata/haxelib/heaps/git/hxd/BitmapData.hx:394: characters 26-57 : Class<flash.utils.ByteArray> has no field fromBytes

Why am I getting so many errors trying to compile the most basic of examples? What am I doing wrong, and more importantly, why doesn't the documentation reflect this? I'd like to help out with documentation, but that's only if I can even get up and running to begin with, and if I can't even do that, I've little hope of helping with documentation.

**Comment by ncannasse** [comment]
I haven't looked at heaps/cpp for some time now. ATM the flash version is the mostly maintained, followed by the JS version (which will work well until #115 is fixed). If you want to use heaps/cpp, you have to use it together with hxsdl (https://github.com/ncannasse/hxsdl)

**Comment by TiZ-EX1** [comment]
And hxsdl has only been tested on Windows. I get the sense that this isn't the engine for me if I want to develop on Linux. Thank you.

**Comment by ncannasse** [comment]
Heaps is still in the works, that's the reason it's not been officially released yet. While hxsdl has not been tested on Linux/OSX, it should works pretty well given it's using SDL which is itself crossplatform.
