### ISSUE TITLE
the axis fbx error.

### ISSUE THREAD

**Issue by matrix3d** [ncannasse/heaps#124]
https://www.dropbox.com/s/oo21us3hgi5p5ky/test4fbx.zip?dl=0

this file in 3dmax,the man stand the plane.

but the heaps fbx error.

**Comment by ncannasse** [comment]
Please note that Heaps needs Z-up FBX export, and will convert to Left-Handed coordinates by flipping the X axis.

**Comment by matrix3d** [comment]
not just z-up issue.
the 2 mesh in heaps,have diffrent axis.
but other model viewer,show good,assmip,blender etc

**Comment by matrix3d** [comment]
i see the code,deal the PreRotation simple mul it.but it need not simple mul.

**Comment by ncannasse** [comment]
Could you suggest a patch for it ?

**Comment by ncannasse** [comment]
I already had some issues with PreRotation, it is a bit hard to deal with it since we also need to do X axis flip to convert from FBX RightHanded to HMD LeftHanded. It become very hard when you have some skinned meshes which transposition matrixes might also be affected by PreRotation. If you can find a way to properly support PreRotation it will be helpful.

**Comment by matrix3d** [comment]
I had some idea,but not the best,but it better than before.
http://matrix3d.github.io/assets/native3d/modelviewer/
this is a app,can view fbx,as you see,it have better(not perfect) prerotation.
it easy code,just anim_matrix= anim_matrix * joint_matrix
https://github.com/matrix3d/FlashShader/blob/master/example/src/gl3d/parser/fbx/FbxParser.as#L504
and this parser,also can parser the binfbx format.
but I know,the best code is the blender_fbxformat,or assimp fbxformat.
but those too compx

**Comment by ncannasse** [comment]
We don't store full matrixes in HMD animation, but separate pos,rot,scale which is more compact and allows us to interpolate each of them separately. So it means that preRotation needs to be taken into account either at the geometry level or into each animation frame (pos,scale,rot) information.

**Comment by matrix3d** [comment]
yes need mul the local matrix

**Comment by ncannasse** [comment]
I have included support for PreRotation in HMD recently, I cannot test with the provided model since the link is no longer working.
