### ISSUE TITLE
Unable to compile examples on Linux

### ISSUE THREAD

**Issue by osakared** [ncannasse/heaps#127]
I wanted to get acquainted with heaps even though the author doesn't consider it stable enough yet.

I installed heaps with `haxelib git heaps https://github.com/ncannasse/heaps.git`, hxsdl with `haxelib git hxsdl https://github.com/ncannasse/hxsdl.git` and other dependencies were available without having to use git.

I then cloned this repo and made obvious modifications to the hxsdl in my path to get it compiling on linux (e.g., SDL.h into SDL/SDL.h). Then going into samples/2d and doing `haxe 2d_ogl.hxml` it craps out on:

    ./src/sdl/GL.cpp:63:24: error: ‘GLLoadAPI’ was not declared in this scope
    Error: ./src/sdl/GL.cpp: In static member function ‘static bool sdl::GL_obj::init()’:
    ./src/sdl/GL.cpp:63:24: error: ‘GLLoadAPI’ was not declared in this scope
      bool tmp = (GLLoadAPI() == (int)0);  HX_STACK_VAR(tmp,"tmp");
                            ^
    In file included from include/sdl/GL.h:9:0,
                     from ./src/sdl/GL.cpp:4:

It looks like that's in an `#ifdef _WIN32` block which makes me think something's spuriously setting that even though I'm not in Windows. If I delete that whole block or set to #if 0, I get:

    Error: ./src/sdl/Sdl.cpp: In static member function ‘static Void sdl::Sdl_obj::init()’:
    ./src/sdl/Sdl.cpp:53:19: error: ‘timeBeginPeriod’ was not declared in this scope
      timeBeginPeriod(1);
                       ^
    ./src/sdl/Sdl.cpp: In static member function ‘static Void sdl::Sdl_obj::quit()’:
    ./src/sdl/Sdl.cpp:204:17: error: ‘timeEndPeriod’ was not declared in this scope
      timeEndPeriod(1);

Strangely, if I modify that file, it gets changed back, preventing me from going further, so I can't even do dirty hacks to get it working until I understand how this works better. Is the focus just on Windows and flash for now? Should I wait a couple of months before playing with this?

**Comment by ncannasse** [comment]
Sdl.cpp is generated from hxsdl/sdl/Sdl.hx.
Does adding the following in the @:cppFileCode data at the top of the class help ?

```
#ifndef _WIN32
#	define timeBeginPeriod(_)
#end
```

**Comment by ncannasse** [comment]
But you'll still need a way to resolve the GL API (the block you have #if 0), unless your Linux headers already have support for OGL3+

**Comment by ncannasse** [comment]
FYI I have dropped hxsdl support in favor of Heaps/HL and Heaps/Lime (contributed by @pperidont)
