### ISSUE TITLE
Fbx animation parser bug

### ISSUE THREAD

**Issue by dairectx** [ncannasse/heaps#128]
In some case, animation is not parsered correctly( no error, just wrong animcurve time? ).

---------------
A sample fbx file has sended to auther's mail.

**Comment by ncannasse** [comment]
It seems that the animation was not baked: some anim curves only have 3 values of the 30 frames. Check Bake Animation when exporting from 3DS Max.

**Comment by dairectx** [comment]
Thanks! I'll check it asap.
