### ISSUE TITLE
Loading Assets

### ISSUE THREAD

**Issue by ncannasse** [ncannasse/heaps#129]
We should provide out of the box an asset packager + loader (similar to Embed) which would create a PAK file, then load it at runtime with a progress bar + logo before starting the App.

**Comment by dairectx** [comment]
I think the origion purpose of the discuss in the mailinglist is that he want to load any model/texture... at runtime( async ). 
It is not difficult to implement it based on FileSystem. But the relative api chain will be broken(Res.Res_XXX.toYYY() ).

**Comment by ncannasse** [comment]
Once you have bytes you can turn them into resources with hxd.res.Any

**Comment by ncannasse** [comment]
Done in c04f41ccc90c89f5c773064c9fd109220bdddc8f
