### ISSUE TITLE
TMax3 size?

### ISSUE THREAD

**Issue by daisuda** [ncannasse/heaps#135]
In ParticleShader.hx 
`@param var rotationAxis : Mat3;`
This param size is 9 in theory.
But when fillparam and upload to gpu, heap use 3 vec4, so actually size is 12.
Then the params in  array will override each other( color, rotationAxis, size  ).
So the particle cannot rotate correctly.
There are two simple( maybe stupid ) ways to fix this:
One is use `@param var rotationAxis : Mat3x4;`
The other one is increasing TMat3 size to 12.

**Comment by ncannasse** [comment]
Tell me if it works better now

**Comment by daisuda** [comment]
Thanks, it works.
But how about this https://github.com/ncannasse/heaps/blob/cccabef390191d74d621c12209211a3341be3afe/hxsl/Ast.hx#L406 ?
