### ISSUE TITLE
controls in an affective manner

### ISSUE THREAD

**Issue by lewislepton** [ncannasse/heaps#137]
so i am just really getting used to heaps. and on looking at the source code for the samples, plus some working LD games im still trying to wrap my head around some things.

one thing is getting controlls in and working a good way.

now this works without fail
```
if (hxd.Key.isPressed(hxd.Key.UP)) {
			bmp.x += _speed;
		}
```

but whilst that is all well and good doing something like this [which i would prefer] does not work. and no matter if i put anything as an argument to `_key` it still crashes
```
public var _key:hxd.Key;
		if (_key) {
			//
		}
```

as such that is what im after in getting to work. so rather than typing out the first one again and again. im just looking for pointers into proper ways etc etc

obviously ive really started to get into heaps. so these may seem like a stupid question ;)

thanks

**Comment by ncannasse** [comment]
I usually do `import hxd.Key in K` then `K.isPressed(K.UP)` I don't think that's a bad API atm.

**Comment by lewislepton** [comment]
cool. i didnt know. so thank you for that ;)
