### ISSUE TITLE
Building for mobile

### ISSUE THREAD

**Issue by hammeron-art** [ncannasse/heaps#151]
Some info or sample of building to Android or iOS?

**Comment by ncannasse** [comment]
ATM you can compile to mobile using either Heaps/AIR or Heaps/Lime.

For adobe air, simply compile a SWF then use `adt` from AIR SDK for packaging the apk/ipa

For Lime, I'll let @kiroukou comment on the steps

**Comment by hammeron-art** [comment]
I'm looking forward for cpp builds and the build tools of Lime when that PR is completed.

I installed the runtime and got it to make and install an apk with AIR sdk without problem but the application don't work on my Android 4.4.4.
It just show a white screen.

**Comment by ncannasse** [comment]
@hammeron-art try to get the some error reports using either uncaughtException or Adobe Scout.

**Comment by kiroukou** [comment]
@hammeron-art you can check that simple lime project structure here : #152

**Comment by hammeron-art** [comment]
@kiroukou Great!
Hovewer there is a little issue here https://github.com/ncannasse/heaps/blob/master/hxd/res/Image.hx#L91-L92 when compiling for cpp.
i.data is always null when using Lime decoder causing a null object reference.
When I remove the Lime implementation and use the format lib the cpp builds for Windows and Android works fine.

**Comment by kiroukou** [comment]
@hammeron-art thanks for the feedback.   Using directly lime native functions allow an optimal performance, especially on mobile. 

 Which version of lime are you using ?  (We are on current git version that we've rebuilt)  There also may have some of our pull request that are pending for being merged...

Could you also provide a simple sample code to reproduce

**Comment by hammeron-art** [comment]
I get the error with the lime basic sample when hxd.Res.hxlogo.toTexture() is called.
I'm using the oficial last haxelib release 2.9.0.

I copied the code from https://github.com/motion-twin/lime/blob/mt_gamebase/lime/graphics/format/PNG.hx and it works so the issue is in fact the current lime version.

**Comment by ncannasse** [comment]
Lime support has been merged into Heaps, I think this is fixed, open a new issue if not.
