### ISSUE TITLE
Linux + mesa + lime : shaders not working

### ISSUE THREAD

**Issue by jeangit** [ncannasse/heaps#155]
Hello,

The now famous sample __/git/samples/basic__ is not working with mesa.

As i use Linux, i'm using lime but i don't think it's related this time.

__haxelib run lime test linux__ compiles well, but hangs at execution on a shader error.

I don't know if it's a mesa problem, or a problem inside the Intel's Xorg driver.

Depending on the codepath of the driver (i've tested with Intel haswell and skylake GPU), you get a cryptic error message about shader or nothing (empty string as error reason).

The cryptic error message was something about an __invalid definition of struct mat3x4__.
As __struct__ is a keyword presents in all flavours of OpenGL core, i suspect something else.

By trial and errors, i've discovered that changing version of shader to GL-ES 1.00 made the sample working (as mesa supports GL-ES in 1.00).

So, i force Intel driver to use mesa-EGL (the gl-es part of mesa)

In __basic_lime.xml__

```
 <haxedef name="mesa" value="" />
```

And i've added the condition in __hxsl/GlslOut.hx__

```
 #if((cpp && mobile)||js||mesa) //added «mesa»
 decls.push("#version 100");
 #else
 decls.push("#version 130");
```

It's working with the above modifications.

BTW, it's working without modifications with nvidia binary driver.

**Comment by ncannasse** [comment]
What if you don't have #version ?
@kiroukou I think we should maybe add #version in GlDriver instead of GLSLOut since we can perform some runtime detection there

**Comment by kiroukou** [comment]
Totally agree.
I've let the comment for that purpose, but changing this is making a
dependency (requirement) between 2 modules (package) so i wasn't sure how
to do that correctly in the heaps way  :)
Le 14 mars 2016 20:15, "Nicolas Cannasse" <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
@kiroukou I'm not sure I understand. You can either setup a global GLSLOut.VERSION static from your driver, so it output #version , or add it yourself in the driver once returned by hxsl. Hxsl should never reference the driver anyway

**Comment by jeangit** [comment]
@ncannasse 

If i don't push #version in __GlslOut.hx__ , i get:

```
Error : An error occurred compiling the shaders: 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER


precision mediump float;
struct mat3x4 { vec4 a; vec4 b; vec4 c; };
(...)
```

BTW, the error i get with __#version 130__ is:

```
Error : An error occurred compiling the shaders: 0:3(8): error: syntax error, unexpected MAT3X4, expecting IDENTIFIER or TYPE_IDENTIFIER or NEW_IDENTIFIER or '{'


#version 130
precision mediump float;
struct mat3x4 { vec4 a; vec4 b; vec4 c; };
vec3 m3x4mult( vec3 v, mat3x4 m) { vec4 ve = vec4(v,1.0); return vec3(dot(m.a,ve),dot(m.b,ve),dot(m.c,ve)); }
```

I don't see what is the problem, __struct__ is a valid datatype even in glsl 130.
Intel driver is compatible with glsl 130 (cannot go above for the moment, but 130 is okay).

Tell me if i can do something more.

**Comment by ncannasse** [comment]
`mat3x4` is now generated as `_mat3x4` which should address the issue.
