### ISSUE TITLE
In the samples : Unknown identifier : loadingTextureColor

### ISSUE THREAD

**Issue by jeangit** [ncannasse/heaps#156]
_OS:_ Arch Linux 64
_Heaps version:_ latest git
_Where:_ all the samples which are using the function __loadingTextureColor__.

_How to reproduce:_
When compiling with Lime, i get this error:

```
git/samples/world$ haxelib run lime test linux                               
/home/jeangit/haxelib/heaps/git/h3d/impl/GlDriver.hx:245: characters 35-54 : Unknown identifier : loadingTextureColor
/home/jeangit/haxelib/heaps/git/h3d/impl/GlDriver.hx:245: characters 56-75 : Unknown identifier : loadingTextureColor
```

Without surprises, get the same error with javascript generation:

```
git/samples/world$ haxe -js -main Main -lib heaps -dce full
/home/jeangit/haxelib/heaps/git/h3d/impl/GlDriver.hx:245: characters 35-54 : Unknown identifier : loadingTextureColor
/home/jeangit/haxelib/heaps/git/h3d/impl/GlDriver.hx:245: characters 56-75 : Unknown identifier : loadingTextureColor
```

Looking at __GlDriver.hx__:
```
if( t == null || t.isDisposed() )
    t = h3d.mat.Texture.fromColor(loadingTextureColor,(loadingTextureColor>>>24)/255);
```

I didn't found where _loadingTextureColor_ was defined (even a _git grep loadingTextureColor_ returns nothing else than the line above.)

Well, tell me if i can do something to help… thank you.

**Comment by ncannasse** [comment]
That's some recent change, it's been moved to h3d.mat.Defaults
