### ISSUE TITLE
ttf with cpp target is working

### ISSUE THREAD

**Issue by jeangit** [ncannasse/heaps#169]
Hello,

NB: the reference i make to the the documentation is not the one on this website (which doesn't address the subject). It is the one in git tree: _haxelib/heaps/git/doc/ref.html_

So, the documentation says you cannot use TTF fonts with CPP target.

> To instancied a h2d.Font we must have:
> a bitmap and his font attached file (customFont.fnt) or a True Type font (exept in C++).

That said, the sample given in the source tree ( _sample/2d_ ) seems to confirm that.
The ttf font loading is skipped if target is CPP :

```
    #if !cpp
    // load a true type font, can be not very high quality
    // la font se situe ici: ../Res/trueTypeFont.ttf
    // elle est chargée grâce à la classe res/FileTree.hx
		var font = hxd.Res.trueTypeFont.build(64);

    ( … )

    // set the text position
    tf.x = 20;
    tf.y = s2d.height - 80;
    #end
```

But reading the source of the res loader for TTF ( _res/FileTree.hx_ )

```
 } else if( isJS || isCPP ) {
           switch( ext.toLowerCase() ) {
           case "ttf" if( isJS ):
                   Embed.doEmbedFont(name, fullPath, options.fontsChars);
                   embedTypes.push("hxd._res." + name);
                   return true;
``` 

i've believed that CPP was supported (i've just seen the _if (isJS)_ conditionnal, when typing this bug report).

So, believing that, i've just commented the conditionnal in _sample/2d_ ( the block « #if !cpp … #end » is now compiled inconditionally).
And when exporting to linux native, with CPP target, i've seen the TTF font appearing, just like in the JS target.

So, it seems you can use TTF fonts even in CPP targets (but i don't know where the support is in the sources).

I've did some searches with git history, but didn't find changes about this.

My question is: is it safe to think that TTF fonts can be used with CPP target ?

Thank you.

ps : i understand that it's not exactly a bug, so i'm bothered to write kind of things like these here. May be there is a better place to discuss those sort of things, so tell me please.

**Comment by ncannasse** [comment]
ping @kiroukou

**Comment by kiroukou** [comment]
Hello,

We do have TTF fonts working on native platforms using Lime.
So far, the official repo of lime seens dead, so you'll need our current fork here : https://github.com/motion-twin/lime/tree/mt_light   (light meaning we removed some features we do not need from lime).

I also have a pull request to make on heaps ir order to prived our latest improvements on native.  This should be done next week in the worst case , meanwhile you can check our fork here : https://github.com/motion-twin/heaps/tree/lime

++

**Comment by ncannasse** [comment]
@kiroukou @pperidont please submit some patches to sync with Heaps master.

**Comment by kiroukou** [comment]
I don't Have access To or anymore, so i let pperidont manage this.

Le 25 sept. 2016 14:55, "Nicolas Cannasse" <notifications@github.com> a
écrit :
