### ISSUE TITLE
Several samples doesn't compile on OSX

### ISSUE THREAD

**Issue by endel** [ncannasse/heaps#173]
Hi there,

This library looks great, unfortunately I couldn't build some samples though.

Here's what I get:

**network**

```
$ haxe network.hxml
/usr/local/Cellar/haxe/haxelib/heaps/git/hxd/net/Macros.hx:174: characters 13-40 : Class<haxe.macro.Context> has no field followWithAbstracts
/usr/local/Cellar/haxe/haxelib/heaps/git/hxd/net/Macros.hx:880: characters 13-32 : Class<haxe.macro.Context> has no field resolveType
/usr/local/Cellar/haxe/haxelib/heaps/git/hxd/net/Macros.hx:888: characters 13-32 : Class<haxe.macro.Context> has no field resolveType
/usr/local/Cellar/haxe/haxelib/heaps/git/hxd/net/Serializable.hx:3: characters 2-11 : Build failure
```

**shadows**

```
$ haxe shadows.hxml
/usr/local/Cellar/haxe/haxelib/heaps/git/h3d/impl/GlDriver.hx:226: characters 45-102 : Type not found : hl.types.ArrayBase
/usr/local/Cellar/haxe/haxelib/heaps/git/h3d/impl/GlDriver.hx:235: characters 44-100 : Type not found : hl.types.ArrayBase
```

**sound**

```
$ haxe sound.hxml
Sound.hx:33: characters 2-27 : Class<hxd.Res> has no field haunted_intro_ogg
Sound.hx:33: characters 45-69 : Class<hxd.Res> has no field haunted_loop_ogg
/usr/local/Cellar/haxe/haxelib/heaps/git/hxd/snd/OggData.hx:28: lines 28-35 : Field writeFloat is inlined and cannot be overridden
```

Some of them compile without errors, such as `basic`, `bounds`, `comps`, `quat`, etc.

Am I missing something? Does it compile on Windows?
Cheers!

**Comment by ex** [comment]
It doesn't compiles on Windows for OpenGL also with:
````
/usr/local/Cellar/haxe/haxelib/heaps/git/h3d/impl/GlDriver.hx:226: characters 45-102 : Type not found : hl.types.ArrayBase
/usr/local/Cellar/haxe/haxelib/heaps/git/h3d/impl/GlDriver.hx:235: characters 44-100 : Type not found : hl.types.ArrayBase
````
Using latest github version and Haxe 3.3. RC1

**Comment by ncannasse** [comment]
Some samples will compile several targets, including `hl` which is a new experimental target. You can ignore these errors as long as the compilation has output `.js` and `.swf` files.

**Comment by ex** [comment]
I was interested in the openGL versions, the JS and SWF of the ones I was testing were fine.

**Comment by ncannasse** [comment]
You should be able to compile the Cpp versions by using hxsdl. Not all
samples are building it.
Le 25 juin 2016 5:56 PM, "Laurens Rodriguez" <notifications@github.com> a
écrit :

**Comment by Frogmellon** [comment]
The 2d\2d_ogl sample gives the same error building on Windows, and from the hxml file should be using hxsdl.

`C:\HaxeToolkit\haxe\lib\heaps/git/h3d/impl/GlDriver.hx:226: characters 74-101 : You cannot access the hl package while targeting cpp (for hl.types.ArrayBase).`

Is there any way to build the native targets? Anything I can do to track this down?

**Comment by ex** [comment]
Can't help is not compiling for me either on Windows, I have installed hxsdl

**Comment by ncannasse** [comment]
I have fixed all the `hl` related bugs, and I have reworked the samples so the projects files are now generated for all platforms. Remaining issue for Heaps/Lime is tracked here https://github.com/ncannasse/heaps/issues/185
