### ISSUE TITLE
MaterialProps and DefaultMaterialProps types expected

### ISSUE THREAD

**Issue by mepsoid** [ncannasse/heaps#176]
Can't compile any sample by HaxeDevelop, opening and running samples/draw for example, leads to the following errors:

C:\HaxeToolkit\haxe\lib\heaps/git/h3d/mat/DefaultMaterialProps.hx:90: characters 2-55 : { shadows : h3d.mat.ShadowsMode, kind : h3d.mat.MaterialKind, cull : Bool } should be h3d.mat.MaterialProps
C:\HaxeToolkit\haxe\lib\heaps/git/h3d/mat/DefaultMaterialProps.hx:90: characters 2-55 : { shadows : h3d.mat.ShadowsMode, kind : h3d.mat.MaterialKind, cull : Bool } should be h3d.mat.DefaultMaterialProps

**Comment by ncannasse** [comment]
Ah that's a 3.3 feature, I'll fix

**Comment by ncannasse** [comment]
closed by 98c6ea61b04d1fe64159cf52142786b9e759a5c3
