### ISSUE TITLE
Lost type hl.types.ArrayBase

### ISSUE THREAD

**Issue by mepsoid** [ncannasse/heaps#177]
Thanks for closing issue #176. Now some samples for example sample/skin demands hl.types.ArrayBase type when using hxsdl library:
C:\HaxeToolkit\haxe\lib\heaps/git/h3d/impl/GlDriver.hx:226: characters 45-102 : Type not found : hl.types.ArrayBase

**Comment by mightymarcus** [comment]
Yes. I got the blues too. Samples are not working. Only errors all around.

**Comment by ncannasse** [comment]
792a82da59507bbdd236d4554343ea5c00c1bcae should have fixed it.

**Comment by mightymarcus** [comment]
Thanks.
