### ISSUE TITLE
Developing on Linux with heaps

### ISSUE THREAD

**Issue by emugel** [ncannasse/heaps#181]
On Linux, the current maximum Debug version of Flash is 11.2, 
whereas the documentation indicates a minimal version of Flash 11.8.

Is this a hard restriction? 
Would like to know what we can expect (from Adobe, not so much I guess,
but are there different features in Flash plugin 11.8 ?)

**Comment by ncannasse** [comment]
You can use Heaps/WebGL or other targets instead of Flash on Linux. I don't think there's support for Stage3D on Linux ATM (only through Chrome Plugin).
