### ISSUE TITLE
DOMStringMap

### ISSUE THREAD

**Issue by vlad-v** [ncannasse/heaps#184]
Error when importing a hxd package: 
C:\SDK\Haxe\haxe\std/js/html/DOMElement.hx:39: characters 29-41 : Type not found : DOMStringMap

Project-Libraries: 
heaps 

Additional Compiler Options:
 -D resourcePath="res"

Environment:
HaxeDevelop 5.1.1.1 ( master#167008dca57)
Win7 :: 32bit :: Microsoft Windows [Version 6.1.7601]
cmd>haxelib list
actuate: [1.8.7]
box2d: [1.2.3]
flixel: [4.1.1]
format: [3.2.1]
halk: [git]
heaps: [git]
hscript: [2.0.7]
hxcpp: [3.3.49]
kha: [16.1.2] git
layout: [1.2.1]
lime-samples: [2.6.0]
lime: 2.9.1 3.1.0 [3.2.0]
moon-ai: [0.1.0]
moon-core: [1.1.1]
msignal: [1.2.4]
nme: [5.6.4]
openfl-samples: [4.0.0]
openfl: 3.6.1 4.1.0 [4.2.0]
starling: [0.5.7]
swf: [2.2.4]

**Comment by ncannasse** [comment]
Seems like something is broken with you haxe install since the error is inside a Haxe std file and is not related to Heaps.
