### ISSUE TITLE
Are the new (generated) samples ready for openfl / lime ? 

### ISSUE THREAD

**Issue by nixxle** [ncannasse/heaps#185]
If I CMD into /samples/build/base3D and run 

`openfl test windows`

I get this: 
**LimeApp.hx:4: characters 18-24 : Type not found : Base3D**

I have this with all the samples, and I guess I am not doing this right?

**Comment by ncannasse** [comment]
I did fix the class path, but there are some remaining compile issues in `LimeStage.hx` , which does not seem to be compatible with latest OpenFL/Lime (3.2.1 installed here).
Ping @pperidont

**Comment by ncannasse** [comment]
Please check again

**Comment by ojlab** [comment]
Thanks, totally works now! Runs realy well too. We can start porting our Away3D game over to heaps now.

**Comment by nixxle** [comment]
Thanks, totally works now! Runs realy well too. We can start porting our Away3D game over to heaps now.
