### ISSUE TITLE
What versions of Lime/OpenFL are supported, and how to run the samples with it?

### ISSUE THREAD

**Issue by jeremyfa** [ncannasse/heaps#196]
Hello, a lot of things look nice on Heaps, but I got no luck when trying to run it with Lime/OpenFL.

It would be useful to know (and specify in the readme) which lime/openfl version are supported, in order to know how to run the sample(s) on it. Right now, I don't know if I should grab latest OpenFL4/Lime3 versions or stick with OpenFL3/Lime2.

As I would have expected, I didn't make it work when running `openfl test` in the samples directory as specified in the readme, because there is no `project.xml` file there. Do we have to take a project file from the `samples/templates` directory manually first? Or is there a better option? Another command to run before? If so, it would be nice to make it clear in the readme as well maybe?

Thanks!

**Comment by ncannasse** [comment]
I'm not familiar with OpenFL and I don't maintain the port for it, @pperidont does. Each project generates a `<name>_lime.xml` based on this template https://github.com/ncannasse/heaps/blob/master/samples/templates/__name_lime.xml , I'm not sure which version is required to support it.
Ping @jgranick while I'm at it :)

**Comment by jeremyfa** [comment]
Thanks, I figured out that I had to run `haxe gen.hxml` inside the `samples` directory, then found by reading at the Generator.hx file code that it puts the project files in the `samples/build/` directory (but I wished these informations could have been easily found in the readme or in the Getting Started wiki page though). As additional information, when running with OpenFL3/Lime2 (on mac), it fails and I get this:

```
lime test base2D_lime.xml cpp
/Users/jeremyfa/Developer/heaps/h3d/impl/GlDriver.hx:805: characters 3-9 : Unknown identifier : mrtExt
/Users/jeremyfa/Developer/heaps/h3d/impl/GlDriver.hx:804: lines 804-805 : Void should be Bool
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:297: characters 3-27 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:298: characters 3-33 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:299: characters 3-25 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:301: characters 3-29 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:302: characters 3-27 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:303: characters 3-27 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:304: characters 3-23 : Warning : This case is unused
/Users/jeremyfa/Developer/heaps/hxd/impl/LimeStage.hx:320: characters 3-35 : Warning : This case is unused
```

I would be useful to know, at least, if it fails because I use the wrong Lime/OpenFL version, or because there is really a problem (the error above) with Heaps that needs to be fixed? Right now it's pretty unclear for me :(

**Comment by ncannasse** [comment]
I have just fixed the issue.
Regarding samples build tutorial, I think that's precisely what's written in the README on https://github.com/ncannasse/heaps no? Where was mentioned otherwise?

**Comment by jeremyfa** [comment]
Oh right, I might have read too quickly, sorry about that, my bad! Thanks a lot for the fix!
