### ISSUE TITLE
Usability enhancements

### ISSUE THREAD

**Issue by cwkx** [ncannasse/heaps#58]
h3d seems great, however I think new users could benefit from:
1. Add an Install section to README.md explaining how to get the latest version with dependencies from git: haxelib git format https://github.com/HaxeFoundation/format.git etc
2. Add a more complete sample. For example a simple "game" with some suggested project structure, a tilemap background, sound, and both an animated .fbx model and animated sprite (even if just a stretching cube or something) responding to some keyboard input.

**Comment by R32** [comment]
I have been waiting for a year now ...

**Comment by ncannasse** [comment]
I started writing a bit of documentation here (https://raw.githubusercontent.com/ncannasse/heaps/master/doc/ref.html), but it's far from being complete, quite busy with Evoland2 atm, I'm planing to spend some times polishing + documenting heaps after we release
