### ISSUE TITLE
Merging back with MotionTwin's branch

### ISSUE THREAD

**Issue by delahee** [ncannasse/heaps#83]
Hi bro,

i list here what is needed for MotionTwin to be brought back in the fold, the list is long but there are priority :)

Vital list for adequate h3d efficiency on cpp : 
- check everything compiles with nme/lime or openfl whatever you choose
- backport h2d.text/hxd.res.FontBuilder UTF8 
- ~~backport shader context lost~~
-~~ backport context lost (problem resides in manifests , other minor issues seems processed)~~
- backport improvement on low level buffer management ( transtyping and what backs floatbuffer etc..)
- backport hxd.FloatStack ( gigatons of realloc avoided ) in tilegroup etc...
- ~~shader precision control is needed / backport them~~
- allow emit or static draw on sprites (static buffer are much more faster to draw) => In fact we shoud have a virtual "renderer" interface because mobile games are so sensitive to perf that the ideal scenario is to have control over what is statically drawn and what is not.

Perf needs
- backport spritebatch improvements ( can be converted back to float stack )
- ~~backport h2d.drawable shader improvements~~ (now easy with variable precision qualifiers)
- backport h2d.matrix rewrites
- add Sprite.width Sprite.height
- ~~backport outline improvements~~

Workflow needs [should be fairly easy]: 
- refactor h3d.fmt.h3d not to pollute the main library
- Add morph support (should be easy)
- Add pvr support (should be easy)

optional Improvements to backport old projects
- port hxd.Float32 ( fairly easy )
- backport h2d.css improvements
- ~~backport render target /render zone push pop from engine~~
- backport render target modification
- ~~backport cached bitmap which now allow recursive render targets~~
- ~~add rim support~~ can be done using custom shaders

..and many more

**Comment by ncannasse** [comment]
I'll close that for now if you don't mind :)
