### ISSUE TITLE
Dirty gpu buffer management

### ISSUE THREAD

**Issue by delahee** [ncannasse/heaps#94]
Any gpu buffer that has been modified and submitted to the gpu this frame should never be allocated until next frame 

( fix is very easy, takes 2 lines )

This usually represent a 10% speed improvement.

**Comment by ncannasse** [comment]
Fixed slightly differently (see  #143)

**Comment by delahee** [comment]
It doesn't look ok to me ( ex spritebatches buffers may be reused next
frame ) so I suggest you keep it open... but as you wish...

2016-02-09 18:32 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Closed #94 <https://github.com/ncannasse/heaps/issues/94>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncannasse/heaps/issues/94#event-544662361>.
>



-- 
David Elahee
