### ISSUE TITLE
h2d.Unordered

### ISSUE THREAD

**Issue by delahee** [ncannasse/heaps#96]
Sometimes emitted tiles should be reordered to disrespect user hierarchy and to be allowed to be rendered wayyyyy faster.

for example alternating text and images could be batched as texts then images with a z value for every tile thus disminishing context changes.

h2d.Unordered would allow substitution of the current render context with a deferred one.

**Comment by ncannasse** [comment]
Will close for now, please submit a PR if still interested. I think it somehow overlaps with SpritBatch

**Comment by delahee** [comment]
this is very different but yep, ok to close.
