### ISSUE TITLE
Support both NME and openfl

### ISSUE THREAD

**Issue by delahee** [ncannasse/heaps#97]
CC @pperidont
I know one might freak out but...Since those codebases are getting apart each other and motion twin current arch is based on openfl (and cannot be migrated very fast) , We'll have to have a transition where both openfl and nme should be supported. maybe we could just do it by a simple "remap" I don't know but the issue is real.

**Comment by ncannasse** [comment]
I'm not planning to work on this, submit a PR if you wish.
