### ISSUE TITLE
Custom Renderer and RT

### ISSUE THREAD

**Issue by ncannasse** [ncannasse/heaps#98]
Currently when rendering the default pass we do setTarget(null), which prevents to override render in the following way:

```
override function render() {
        var target = allocTarget("tmp");
        setTarget(target);
         // render to target
        super.render();
         // post process
 }
```

We need instead to manage the RT in a better way, for instance each pass should switch back to the previous RT when finished. In order to minimize the actual number of RT switches, some optimizations are required at the driver level.

**Comment by delahee** [comment]
Agreed. that what we do manually.

2015-03-14 12:25 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Currently when rendering the default pass we do setTarget(null), which
> prevents to override render in the following way:
>
> override function render() {
>         var target = allocTarget("tmp");
>         setTarget(target);
>          // render to target
>         super.render();
>          // post process
>  }
>
> We need instead to manage the RT in a better way, for instance each pass
> should switch back to the previous RT when finished. In order to minimize
> the actual number of RT switches, some optimizations are required at the
> driver level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncannasse/heaps/issues/98>.
>



-- 
David Elahee

**Comment by ncannasse** [comment]
Done in 6b9fab120b4191aae0c26dcb73e453dc983fa40a

**Comment by delahee** [comment]
Awesome !

2015-11-22 12:17 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Done in 6b9fab1
> <https://github.com/ncannasse/heaps/commit/6b9fab120b4191aae0c26dcb73e453dc983fa40a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncannasse/heaps/issues/98#issuecomment-158748002>.
>



-- 
David Elahee
